### ISSUE TITLE
Explain build system

### ISSUE THREAD

**Issue by thurt** [omphalos/inductive.js#8]
Very interesting ideas in inductive paradigm. I am just getting started. I tried to make an add function after the helloworld example. But I don't understand the error. A better explanation of the execution model / build system might help. Thanks!

``` javascript
require('inductive.js').globals()

var adder = specify('adder',
  given(1, 2, shouldReturn(3)),
  use('Number+')

run(adder)

saveAll()
```

`Error: Cannot run a Specification that takes arguments: run adder`

**Comment by omphalos** [comment]
Hi @thurt.  Thanks for taking a look at inductive.js!

`run` causes a function call to written to the .js file when you run the .i.js file.  It expects a specification that takes no arguments.  In this case it thinks you want to write a file that looks like this:

``` js
function adder(arg0, arg1) {
  return arg0 + arg1;
}

adder()
```

But it doesn't make much sense to call `adder` without any arguments, since it expects two arguments, so inductive.js spits out that error.

If you are going to use `run` you need to pass it a specification that takes no arguments instead.

Hope this helps.  I'm not sure if this answers everything you're asking about the build system.  Please let me know if you want more detail on something in particular and I will be happy to try to answer.

**Comment by thurt** [comment]
Ah thanks! I thought `run` was part of generating the function, not running it. I will have a go at this again
